version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: syncdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    networks:
      - backend

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: universal-sync-server
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - minio
    networks:
      - backend

volumes:
  postgres-data:
  minio-data:

networks:
  backend:
